/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * @author Saurabh
 */
public class AcademicAttributes extends javax.swing.JFrame {
    public static boolean tenthBoo = false,twelthBoo = false,gradBoo = false,pubBoo = false,acadBoo = false,scholBoo = false,workBoo = false,coCurBoo = false,miscBoo = false;

    /**
     * Creates new form AcademicAttributes
     */
    public AcademicAttributes() {
        initComponents();
        setBounds(500, 520, 550,400);
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tenth = new javax.swing.JCheckBox();
        twelth = new javax.swing.JCheckBox();
        graduation = new javax.swing.JCheckBox();
        publication = new javax.swing.JCheckBox();
        academic = new javax.swing.JCheckBox();
        scholastic = new javax.swing.JCheckBox();
        workshop = new javax.swing.JCheckBox();
        coCur = new javax.swing.JCheckBox();
        misc = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel1.setText("Please Select The Attributes You Want In Your Resume");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(145, 19, 342, 16);

        b1.setText("Back");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(10, 304, 59, 25);

        b2.setText("Next");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(443, 304, 57, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 130, 90);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tenth.setBackground(new java.awt.Color(255, 255, 255));
        tenth.setText("10th Standard");
        tenth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenthActionPerformed(evt);
            }
        });

        twelth.setBackground(new java.awt.Color(255, 255, 255));
        twelth.setText("12th Standard");

        graduation.setBackground(new java.awt.Color(255, 255, 255));
        graduation.setText("Graduation");

        publication.setBackground(new java.awt.Color(255, 255, 255));
        publication.setText("Thesis/Publications");

        academic.setBackground(new java.awt.Color(255, 255, 255));
        academic.setText("Academic Achievements");

        scholastic.setBackground(new java.awt.Color(255, 255, 255));
        scholastic.setText("Scholastic Achievements");
        scholastic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scholasticActionPerformed(evt);
            }
        });

        workshop.setBackground(new java.awt.Color(255, 255, 255));
        workshop.setText("Seminars/Workshops Attended");

        coCur.setBackground(new java.awt.Color(255, 255, 255));
        coCur.setText("Co-Curricular Activities");

        misc.setBackground(new java.awt.Color(255, 255, 255));
        misc.setText("Miscellaneous");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(misc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coCur, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workshop, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scholastic, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(academic, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publication, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graduation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twelth, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenth, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(tenth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twelth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graduation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(academic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scholastic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(workshop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(misc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenthActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tenthActionPerformed

    private void scholasticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scholasticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scholasticActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        new AcademicTemplate().setVisible(true);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(tenth.isSelected())
        {
            tenthBoo =  true;
            
        }
        if(twelth.isSelected())
        {
            twelthBoo =  true;
        }
        if(graduation.isSelected())
        {
            gradBoo =  true;
        }
        if(publication.isSelected())
        {
            pubBoo =  true;
        }
        if(academic.isSelected())
        {
            acadBoo =  true;
        }
        if(scholastic.isSelected())
        {
            scholBoo =  true;
        }
        if(workshop.isSelected())
        {
            workBoo =  true;
        }
        if(coCur.isSelected())
        {
            coCurBoo =  true;
        }
        if(misc.isSelected())
        {
            miscBoo =  true;
        }
        this.setVisible(false);
        new FillFormAcademic().setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcademicAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcademicAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcademicAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcademicAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcademicAttributes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox academic;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JCheckBox coCur;
    private javax.swing.JCheckBox graduation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox misc;
    private javax.swing.JCheckBox publication;
    private javax.swing.JCheckBox scholastic;
    private javax.swing.JCheckBox tenth;
    private javax.swing.JCheckBox twelth;
    private javax.swing.JCheckBox workshop;
    // End of variables declaration//GEN-END:variables
}
