/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.html.simpleparser.HTMLWorker;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;

/**
 *
 * @author Saurabh
 */
public class FillFormNonTechnical extends javax.swing.JFrame {

    /**
     * Creates new form FillFormNonTechnical
     */
    public FillFormNonTechnical() {
        initComponents();
         setBounds(600, 600, 600, 550);
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l5.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        
        
        t1.setVisible(false);
        t2.setVisible(false);
        t3.setVisible(false);
        t4.setVisible(false);
        t5.setVisible(false);
        t6.setVisible(false);
        t7.setVisible(false);
        t8.setVisible(false);
        t9.setVisible(false);
        t10.setVisible(false);
        t11.setVisible(false);
        t12.setVisible(false);
        
        showAll();
    }
    
    public final void showAll()
    {
        
        if(NonTechnicalAttribute.acadBoo)
        {
            l1.setVisible(true);
            t1.setVisible(true);
        }
        if(NonTechnicalAttribute.schBoo)
        {
            l2.setVisible(true);
            t2.setVisible(true);
        }
        if(NonTechnicalAttribute.pubBoo)
        {
            l3.setVisible(true);
            t3.setVisible(true);
        }
        if(NonTechnicalAttribute.projectBoo)
        {
            l4.setVisible(true);
            t4.setVisible(true);
        }
        if(NonTechnicalAttribute.resBoo)
        {
            l5.setVisible(true);
            t5.setVisible(true);
        }
        if(NonTechnicalAttribute.internBoo)
        {
            l6.setVisible(true);
            t6.setVisible(true);
        }
        if(NonTechnicalAttribute.certiBoo)
        {
            l7.setVisible(true);
            t7.setVisible(true);
        }
        if(NonTechnicalAttribute.posBoo)
        {
            l8.setVisible(true);
            t8.setVisible(true);
        }
        if(NonTechnicalAttribute.entreBoo)
        {
            l9.setVisible(true);
            t9.setVisible(true);
        }
        if(NonTechnicalAttribute.coCurrBoo)
        {
            l10.setVisible(true);
            t10.setVisible(true);
        }
        if(NonTechnicalAttribute.mooBoo)
        {
            l11.setVisible(true);
            t11.setVisible(true);
        }
        if(NonTechnicalAttribute.addBoo)
        {
            l12.setVisible(true);
            t12.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 459, 59, 25);

        l1.setText("Academic Achievements");
        getContentPane().add(l1);
        l1.setBounds(150, 10, 140, 16);

        l2.setText("Scholastic Achievements");
        getContentPane().add(l2);
        l2.setBounds(150, 50, 140, 16);

        l3.setText("Publications");
        getContentPane().add(l3);
        l3.setBounds(160, 90, 67, 16);

        l4.setText("Projects");
        getContentPane().add(l4);
        l4.setBounds(160, 130, 46, 16);

        l5.setText("Research Projects");
        getContentPane().add(l5);
        l5.setBounds(160, 160, 103, 16);

        l6.setText("Training/ Internships");
        getContentPane().add(l6);
        l6.setBounds(160, 200, 119, 16);

        l7.setText("Certifications");
        getContentPane().add(l7);
        l7.setBounds(160, 240, 74, 16);

        l8.setText("Position of Responsibility");
        getContentPane().add(l8);
        l8.setBounds(160, 280, 140, 16);

        l9.setText("Entrepreneurship");
        getContentPane().add(l9);
        l9.setBounds(160, 320, 90, 16);

        l10.setText("Co- curricular Activities");
        getContentPane().add(l10);
        l10.setBounds(160, 360, 132, 16);

        l11.setText("Moot-Courts");
        getContentPane().add(l11);
        l11.setBounds(160, 390, 70, 16);

        l12.setText("Add On Courses");
        getContentPane().add(l12);
        l12.setBounds(160, 420, 92, 16);
        getContentPane().add(t1);
        t1.setBounds(441, 11, 120, 30);
        getContentPane().add(t2);
        t2.setBounds(441, 49, 120, 30);
        getContentPane().add(t3);
        t3.setBounds(441, 87, 120, 30);
        getContentPane().add(t4);
        t4.setBounds(441, 125, 120, 30);
        getContentPane().add(t5);
        t5.setBounds(441, 163, 120, 30);
        getContentPane().add(t6);
        t6.setBounds(441, 201, 120, 22);
        getContentPane().add(t7);
        t7.setBounds(441, 239, 120, 22);
        getContentPane().add(t8);
        t8.setBounds(441, 277, 120, 22);
        getContentPane().add(t9);
        t9.setBounds(441, 315, 120, 22);
        getContentPane().add(t10);
        t10.setBounds(441, 353, 120, 22);
        getContentPane().add(t11);
        t11.setBounds(441, 391, 120, 22);
        getContentPane().add(t12);
        t12.setBounds(440, 420, 120, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 130, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/project-manager-roll.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 140, 150);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setText("Download Pdf");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate Html Page ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(459, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new NonTechnicalAttribute().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        makeHTML();
        convertToHTML("$f1","&acad",t1.getText(), NonTechnicalAttribute.acadBoo);
        convertToHTML("$f2","&schol",t2.getText(),NonTechnicalAttribute.schBoo);
        convertToHTML("$f3","&pub",t3.getText(),NonTechnicalAttribute.pubBoo);
        convertToHTML("$f5","&proj",t5.getText(),NonTechnicalAttribute.projectBoo);
        convertToHTML("$f4","&res",t4.getText(),NonTechnicalAttribute.resBoo);
        convertToHTML("$f6","&intern",t6.getText(),NonTechnicalAttribute.internBoo);
        convertToHTML("$f7","&certi",t7.getText(),NonTechnicalAttribute.certiBoo);
        convertToHTML("$f8","&pos",t8.getText(),NonTechnicalAttribute.posBoo);
        convertToHTML("$f9","&entre",t9.getText(),NonTechnicalAttribute.entreBoo);
        convertToHTML("$y1","cocurr",t10.getText(),NonTechnicalAttribute.coCurrBoo);
        convertToHTML("$y2","&moot",t11.getText(),NonTechnicalAttribute.mooBoo);
        convertToHTML("$y3","&add",t12.getText(),NonTechnicalAttribute.addBoo);
        convertToHTML("$n1","$name",PersonalDetails.name,true);
        convertToHTML("$n2","$email",PersonalDetails.email,true);
        convertToHTML("$n3","$contact",PersonalDetails.contact,true);
        convertToHTML("$n4","$address",PersonalDetails.address,true);
         convertToHTML("$n5","$discipline",PersonalDetails.discipline,true);
        convertToHTML("$n6","$dob",PersonalDetails.dob,true);
        convertToHTML("$n7","$batch",PersonalDetails.batch,true);
        
          /*try {     
            makePdf();
        } catch (IOException ex) {
//            Exceptions.printStackTrace(ex);
        } catch (DocumentException ex) {
           // Exceptions.printStackTrace(ex);
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new pdftry().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FillFormNonTechnical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FillFormNonTechnical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FillFormNonTechnical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FillFormNonTechnical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FillFormNonTechnical().setVisible(true);
            }
        });
    }

    public void convertToHTML(String field,String value,String attr,boolean boo)
        {
            
            try{
                 BufferedReader in;
                in = new BufferedReader(new FileReader("Allnew2.html"));
                 String str = "";
                 StringBuilder contentBuilder = new StringBuilder();
                 while((str=in.readLine())!=null)
                 {
                        contentBuilder.append(str);
                 }
                 in.close();
                 
                 //String html = "<div><h1>hello</h1><p>hi<p></div";
                String content = contentBuilder.toString();
                String sh = "none";
                
                if(boo == false)
                    content = content.replace(field, sh);
                else 
                    content = content.replace(value, attr);
                // content = content + "<table border='2' cellpadding='15' cellspacing='2' width='80%' align='center'><tr><td> Address:</td> </tr></table>";
                 File f = new File("Allnew2.html");
        
                BufferedWriter bw = new BufferedWriter(new FileWriter(f));
                bw.write(content);
                bw.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        }
    public void makeHTML()
        {
            
            try{
                 BufferedReader in;
                in = new BufferedReader(new FileReader(NonTechnicalTemplate.fName));
                 String str = "";
                 StringBuilder contentBuilder = new StringBuilder();
                 while((str=in.readLine())!=null)
                 {
                        contentBuilder.append(str);
                 }
                 in.close();
                 
                 //String html = "<div><h1>hello</h1><p>hi<p></div";
                String content = contentBuilder.toString();
                
                //else 
                //    content = content.replace(value, attr);
                // content = content + "<table border='2' cellpadding='15' cellspacing='2' width='80%' align='center'><tr><td> Address:</td> </tr></table>";
                 File f = new File("Allnew2.html");
        
                BufferedWriter bw = new BufferedWriter(new FileWriter(f));
                bw.write(content);
                bw.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        }
     /*public void makePdf() throws IOException, DocumentException
    {
        String path = "Allnew2.pdf";
        PdfWriter pdfWriter = null;

        // create a new document
        Document document = new Document();
        pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(
                    path));
        document.open();
        HTMLWorker htmlWorker = new HTMLWorker(document);
        String str = "";
        StringBuilder contentBuilder = new StringBuilder();
        BufferedReader in = null;
        try {
            in = new BufferedReader(new FileReader("Allnew2.html"));

     while ((str = in.readLine()) != null) {

           contentBuilder.append(str);

    }
} catch (IOException e) {
    System.out.print("HTML file close problem:" + e.getMessage());
} finally {
    in.close();

}
String content = contentBuilder.toString();

htmlWorker.parse(new StringReader(content));

document.close();
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
