/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.html.simpleparser.HTMLWorker;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
//import com.sun.security.ntlm.Client;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;



/**
 *
 * @author Saurabh
 */
public class FillFormAcademic extends javax.swing.JFrame {

    /**
     * Creates new form FillFormAcademic
     */
    public FillFormAcademic() {
        initComponents();
         setBounds(600, 600, 500, 450);
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l5.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        
        
        t1.setVisible(false);
        t2.setVisible(false);
        t3.setVisible(false);
        t4.setVisible(false);
        t5.setVisible(false);
        t6.setVisible(false);
        t7.setVisible(false);
        t8.setVisible(false);
        t9.setVisible(false);
        
        showAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public final void showAll()
    {
        
        if(AcademicAttributes.tenthBoo)
        {
            l1.setVisible(true);
            t1.setVisible(true);
        }
        if(AcademicAttributes.twelthBoo)
        {
            l2.setVisible(true);
            t2.setVisible(true);
        }
        if(AcademicAttributes.gradBoo)
        {
            l3.setVisible(true);
            t3.setVisible(true);
        }
        if(AcademicAttributes.pubBoo)
        {
            l4.setVisible(true);
            t4.setVisible(true);
        }
        if(AcademicAttributes.acadBoo)
        {
            l5.setVisible(true);
            t5.setVisible(true);
        }
        if(AcademicAttributes.scholBoo)
        {
            l6.setVisible(true);
            t6.setVisible(true);
        }
        if(AcademicAttributes.workBoo)
        {
            l7.setVisible(true);
            t7.setVisible(true);
        }
        if(AcademicAttributes.coCurBoo)
        {
            l8.setVisible(true);
            t8.setVisible(true);
        }
        if(AcademicAttributes.miscBoo)
        {
            l9.setVisible(true);
            t9.setVisible(true);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        l7 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        l8 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        l9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        l1.setText("10th");
        getContentPane().add(l1);
        l1.setBounds(180, 29, 70, 20);
        getContentPane().add(t1);
        t1.setBounds(286, 29, 80, 30);

        l2.setText("12th");
        getContentPane().add(l2);
        l2.setBounds(180, 54, 60, 20);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(286, 55, 80, 30);

        l3.setText("Graduation");
        getContentPane().add(l3);
        l3.setBounds(148, 86, 100, 20);
        getContentPane().add(t3);
        t3.setBounds(285, 86, 81, 30);

        l4.setText("Thesis/ Publications");
        getContentPane().add(l4);
        l4.setBounds(135, 120, 120, 20);
        getContentPane().add(t4);
        t4.setBounds(285, 117, 81, 30);

        l5.setText("Academic Achievements");
        getContentPane().add(l5);
        l5.setBounds(135, 150, 140, 20);
        getContentPane().add(t5);
        t5.setBounds(285, 153, 81, 30);

        l6.setText("Scholastic Achevements");
        getContentPane().add(l6);
        l6.setBounds(135, 182, 150, 20);
        getContentPane().add(t6);
        t6.setBounds(286, 179, 80, 30);

        l7.setText("Seminar/ Workshops Attended");
        getContentPane().add(l7);
        l7.setBounds(135, 208, 170, 20);
        getContentPane().add(t7);
        t7.setBounds(286, 205, 80, 30);

        l8.setText("Co=curricular Activities");
        getContentPane().add(l8);
        l8.setBounds(135, 234, 170, 20);
        getContentPane().add(t8);
        t8.setBounds(285, 231, 81, 30);

        l9.setText("Miscellaneous");
        getContentPane().add(l9);
        l9.setBounds(135, 262, 150, 20);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 364, 59, 25);
        getContentPane().add(t9);
        t9.setBounds(285, 262, 81, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 140, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/256-256-d7164bd0f63ae028107beabed05eceae-academics.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 120, 130, 100);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setText("Download Pdf");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate Html Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(96, 96, 96))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AcademicAttributes().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        makeHTML();
        convertToHTML("$f1","&10",t1.getText(),AcademicAttributes.tenthBoo);
        convertToHTML("$f2","&12",t2.getText(),AcademicAttributes.twelthBoo);
        convertToHTML("$f3","&grad",t3.getText(),AcademicAttributes.gradBoo);
        convertToHTML("$f5","&acad",t5.getText(),AcademicAttributes.acadBoo);
        convertToHTML("$f4","&thesis",t4.getText(),AcademicAttributes.pubBoo);
        convertToHTML("$f6","&schol",t6.getText(),AcademicAttributes.scholBoo);
        convertToHTML("$f7","&seminar",t7.getText(),AcademicAttributes.workBoo);
        convertToHTML("$f8","&cocurr",t8.getText(),AcademicAttributes.coCurBoo);
        convertToHTML("$f9","&misc",t9.getText(),AcademicAttributes.miscBoo);
        convertToHTML("$n1","$name",PersonalDetails.name,true);
        convertToHTML("$n2","$email",PersonalDetails.email,true);
        convertToHTML("$n3","$contact",PersonalDetails.contact,true);
        convertToHTML("$n4","$address",PersonalDetails.address,true);
        convertToHTML("$n5","$discipline",PersonalDetails.discipline,true);
        convertToHTML("$n6","$dob",PersonalDetails.dob,true);
        convertToHTML("$n7","$batch",PersonalDetails.batch,true);
        
         try
        {
            myconnection obj=new myconnection();
            String q="select * from image where Username=?";
            ResultSet rs;
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1, Login.u);
            
          
            rs=pst.executeQuery();
           
          
            if(rs.next())
            {
                byte[] bo=rs.getBytes("img");
               String b64 = javax.xml.bind.DatatypeConverter.printBase64Binary(bo);
               convertToHTML("$img1","$imgname",b64,true);
               }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
        /*try {     
            makePdf();
            
        } catch (IOException ex) {
            //Exceptions.printStackTrace(ex);
        } catch (DocumentException ex) {
//            Exceptions.printStackTrace(ex);
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new pdftry().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /*public void makePdf() throws IOException, DocumentException
    {
        String path = "Allnew.pdf";
        PdfWriter pdfWriter = null;

        // create a new document
        
        Document document = new Document();
        pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(
                    path));
        document.open();
        HTMLWorker htmlWorker = new HTMLWorker(document);
        String str = "";
        StringBuilder contentBuilder = new StringBuilder();
        BufferedReader in = null;
        try {
            in = new BufferedReader(new FileReader("Allnew.html"));

     while ((str = in.readLine()) != null) {

           contentBuilder.append(str);

    }
} catch (IOException e) {
    System.out.print("HTML file close problem:" + e.getMessage());
} finally {
    in.close();

}
String content = contentBuilder.toString();

htmlWorker.parse(new StringReader(content));

document.close();
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FillFormAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FillFormAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FillFormAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FillFormAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FillFormAcademic().setVisible(true);
            }
        });
    }
    
    public void convertToHTML(String field,String value,String attr,boolean boo)
        {
            
            try{
                 BufferedReader in;
                in = new BufferedReader(new FileReader("Allnew.html"));
                 String str = "";
                 StringBuilder contentBuilder = new StringBuilder();
                 while((str=in.readLine())!=null)
                 {
                        contentBuilder.append(str);
                 }
                 in.close();
                 
                 //String html = "<div><h1>hello</h1><p>hi<p></div";
                String content = contentBuilder.toString();
                String sh = "none";
                
                if(boo == false)
                    content = content.replace(field, sh);
                else 
                    content = content.replace(value, attr);
                // content = content + "<table border='2' cellpadding='15' cellspacing='2' width='80%' align='center'><tr><td> Address:</td> </tr></table>";
                 File f = new File("Allnew.html");
        
                BufferedWriter bw = new BufferedWriter(new FileWriter(f));
                bw.write(content);
                bw.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        }
    public void makeHTML()
        {
            
            try{
                 BufferedReader in;
                in = new BufferedReader(new FileReader(AcademicTemplate.fname));
                 String str = "";
                 StringBuilder contentBuilder = new StringBuilder();
                 while((str=in.readLine())!=null)
                 {
                        contentBuilder.append(str);
                 }
                 in.close();
                 
                 //String html = "<div><h1>hello</h1><p>hi<p></div";
                String content = contentBuilder.toString();
                
                //else 
                //    content = content.replace(value, attr);
                // content = content + "<table border='2' cellpadding='15' cellspacing='2' width='80%' align='center'><tr><td> Address:</td> </tr></table>";
                 File f = new File("Allnew.html");
        
                BufferedWriter bw = new BufferedWriter(new FileWriter(f));
                bw.write(content);
                bw.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
      
        }
    
   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
