/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Saurabh
 */
public class NonTechnicalAttribute extends javax.swing.JFrame {
    public static boolean acadBoo = false,schBoo = false,pubBoo = false, projectBoo=false,resBoo = false,mooBoo = false,certiBoo = false,internBoo = false,posBoo = false,coCurrBoo = false,entreBoo = false,addBoo = false;

    /**
     * Creates new form NonTechnicalAttribute
     */
    public NonTechnicalAttribute() {
        initComponents();
        setBounds(500, 500, 600,450);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        academic = new javax.swing.JCheckBox();
        scholastic = new javax.swing.JCheckBox();
        publications = new javax.swing.JCheckBox();
        projects = new javax.swing.JCheckBox();
        research = new javax.swing.JCheckBox();
        internships = new javax.swing.JCheckBox();
        certifications = new javax.swing.JCheckBox();
        positions = new javax.swing.JCheckBox();
        entrepreneurship = new javax.swing.JCheckBox();
        coCurricular = new javax.swing.JCheckBox();
        mootCourts = new javax.swing.JCheckBox();
        addOn = new javax.swing.JCheckBox();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        academic.setBackground(new java.awt.Color(255, 255, 255));
        academic.setText("Academic Achievements");
        getContentPane().add(academic);
        academic.setBounds(120, 122, 170, 25);

        scholastic.setBackground(new java.awt.Color(255, 255, 255));
        scholastic.setText("Scholastic Achievements");
        getContentPane().add(scholastic);
        scholastic.setBounds(120, 145, 170, 25);

        publications.setBackground(new java.awt.Color(255, 255, 255));
        publications.setText("Publications");
        getContentPane().add(publications);
        publications.setBounds(120, 168, 170, 25);

        projects.setBackground(new java.awt.Color(255, 255, 255));
        projects.setText("Projects");
        getContentPane().add(projects);
        projects.setBounds(120, 194, 170, 25);

        research.setBackground(new java.awt.Color(255, 255, 255));
        research.setText("Research Projects");
        getContentPane().add(research);
        research.setBounds(120, 217, 170, 25);

        internships.setBackground(new java.awt.Color(255, 255, 255));
        internships.setText("Training/Internships");
        getContentPane().add(internships);
        internships.setBounds(120, 243, 170, 25);

        certifications.setBackground(new java.awt.Color(255, 255, 255));
        certifications.setText("Certifications");
        getContentPane().add(certifications);
        certifications.setBounds(120, 266, 170, 25);

        positions.setBackground(new java.awt.Color(255, 255, 255));
        positions.setText("Position of Responsibility");
        getContentPane().add(positions);
        positions.setBounds(120, 291, 170, 25);

        entrepreneurship.setBackground(new java.awt.Color(255, 255, 255));
        entrepreneurship.setText("Entrepreneurship");
        getContentPane().add(entrepreneurship);
        entrepreneurship.setBounds(328, 122, 170, 25);

        coCurricular.setBackground(new java.awt.Color(255, 255, 255));
        coCurricular.setText("Co-Curricular Activities");
        getContentPane().add(coCurricular);
        coCurricular.setBounds(328, 145, 170, 25);

        mootCourts.setBackground(new java.awt.Color(255, 255, 255));
        mootCourts.setText("Moot-courts");
        getContentPane().add(mootCourts);
        mootCourts.setBounds(328, 168, 170, 25);

        addOn.setBackground(new java.awt.Color(255, 255, 255));
        addOn.setText("Add on Courses");
        getContentPane().add(addOn);
        addOn.setBounds(328, 194, 170, 25);

        b1.setText("Back");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(361, 291, 90, 25);

        b2.setText("Next");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(470, 290, 90, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 150, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/technical-capability.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 160, 110, 120);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Please Select The Attributes You Want In your Resume");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 120, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        this.setVisible(false);
        new NonTechnicalTemplate().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(academic.isSelected())
        {
            acadBoo =  true;
        }
        if(scholastic.isSelected())
        {
            schBoo =  true;
        }
        if(publications.isSelected())
        {
            pubBoo =  true;
        }
        if(projects.isSelected())
        {
            projectBoo =  true;
        }
        if(research.isSelected())
        {
            resBoo =  true;
        }
        if(internships.isSelected())
        {
            internBoo =  true;
        }
        if(certifications.isSelected())
        {
            certiBoo =  true;
        }
        if(positions.isSelected())
        {
            posBoo =  true;
        }
        if(entrepreneurship.isSelected())
        {
            entreBoo =  true;
        }
        if(coCurricular.isSelected())
        {
            coCurrBoo =  true;
        }
        if(mootCourts.isSelected())
        {
            mooBoo =  true;
        }
        if(addOn.isSelected())
        {
           addBoo =  true;
        }
        this.setVisible(false);
        new FillFormNonTechnical().setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NonTechnicalAttribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NonTechnicalAttribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NonTechnicalAttribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NonTechnicalAttribute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NonTechnicalAttribute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox academic;
    private javax.swing.JCheckBox addOn;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JCheckBox certifications;
    private javax.swing.JCheckBox coCurricular;
    private javax.swing.JCheckBox entrepreneurship;
    private javax.swing.JCheckBox internships;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mootCourts;
    private javax.swing.JCheckBox positions;
    private javax.swing.JCheckBox projects;
    private javax.swing.JCheckBox publications;
    private javax.swing.JCheckBox research;
    private javax.swing.JCheckBox scholastic;
    // End of variables declaration//GEN-END:variables
}
