/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Saurabh
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
         setBounds(500, 500, 500, 520);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        t3.add("Fav food");
        t3.add("Fav Place");
        t3.add("Fav movie");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        t1 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t3 = new java.awt.Choice();
        label5 = new java.awt.Label();
        t5 = new java.awt.TextField();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        t6 = new java.awt.TextField();
        t7 = new java.awt.TextField();
        t8 = new java.awt.TextField();
        t10 = new java.awt.TextField();
        t11 = new java.awt.TextField();
        t9 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setText("Username:");
        getContentPane().add(label1);
        label1.setBounds(150, 100, 110, 20);

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setText("Password:");
        getContentPane().add(label2);
        label2.setBounds(150, 130, 110, 20);

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setText("Security Question:");
        getContentPane().add(label3);
        label3.setBounds(150, 190, 110, 20);

        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setText("Security Answer:");
        getContentPane().add(label4);
        label4.setBounds(150, 220, 110, 20);
        getContentPane().add(t1);
        t1.setBounds(287, 100, 130, 20);

        t2.setEchoChar('*');
        getContentPane().add(t2);
        t2.setBounds(287, 130, 130, 20);
        getContentPane().add(t4);
        t4.setBounds(287, 220, 130, 20);
        getContentPane().add(t3);
        t3.setBounds(287, 190, 130, 20);

        label5.setBackground(new java.awt.Color(255, 255, 255));
        label5.setText("Confirm Password:");
        getContentPane().add(label5);
        label5.setBounds(150, 160, 110, 20);

        t5.setEchoChar('*');
        getContentPane().add(t5);
        t5.setBounds(287, 160, 130, 20);

        label6.setBackground(new java.awt.Color(255, 255, 255));
        label6.setText("Date of Birth:");
        getContentPane().add(label6);
        label6.setBounds(150, 340, 74, 20);

        label7.setBackground(new java.awt.Color(255, 255, 255));
        label7.setText("Email:");
        getContentPane().add(label7);
        label7.setBounds(150, 250, 39, 20);

        label8.setBackground(new java.awt.Color(255, 255, 255));
        label8.setText("Contact:");
        getContentPane().add(label8);
        label8.setBounds(150, 280, 49, 20);

        label9.setBackground(new java.awt.Color(255, 255, 255));
        label9.setText("Address:");
        getContentPane().add(label9);
        label9.setBounds(150, 310, 53, 20);

        label10.setBackground(new java.awt.Color(255, 255, 255));
        label10.setText("Discipiline:");
        getContentPane().add(label10);
        label10.setBounds(150, 370, 65, 20);

        label11.setBackground(new java.awt.Color(255, 255, 255));
        label11.setText("Batch:");
        getContentPane().add(label11);
        label11.setBounds(150, 400, 38, 20);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6);
        t6.setBounds(287, 250, 130, 20);
        getContentPane().add(t7);
        t7.setBounds(287, 280, 130, 20);
        getContentPane().add(t8);
        t8.setBounds(287, 310, 130, 20);
        getContentPane().add(t10);
        t10.setBounds(287, 370, 130, 20);
        getContentPane().add(t11);
        t11.setBounds(287, 400, 130, 20);
        getContentPane().add(t9);
        t9.setBounds(287, 340, 130, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sign-up-here.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        button1.setLabel("Submit");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        try
        {
            String u,p,sq,sa,cp,e,c,ad,dob,d,b;
            u=t1.getText();
            p=t2.getText();
            if(!Pattern.matches("[a-zA-Z0-9]{4,13}", p))
            {
                JOptionPane.showMessageDialog(this,"Password must be of atleast 4 characters and must not exceed 13 characters");
                return;
            }
            sq=t3.getSelectedItem();
            sa=t4.getText();
            cp=t5.getText();
            if(u.length()==0)
            {
                JOptionPane.showMessageDialog(this,"Please Enter valid username");
                return;
            }
            if(!p.equals(cp))
            {
                JOptionPane.showMessageDialog(this,"Password do not match");
                return;
            }
            e=t6.getText();
            c=t7.getText();
            ad=t8.getText();
            //dob=t9.getDateFormatString();
            Date d1=t9.getDate();
            SimpleDateFormat obj1=new SimpleDateFormat("MM-dd-yyyy");
            String u1=(String)obj1.format(d1);
            
               
            
            d=t10.getText();
            b=t11.getText();
            
            myconnection obj=new myconnection();
            String q1="select * from account where username=?";
            PreparedStatement pst=obj.db.prepareStatement(q1);
            pst.setString(1,u);
            ResultSet rs;
            rs=pst.executeQuery();
            if(!rs.next())
            {
                String q="insert into account(Username,Password,SecurityQ,SecurityA,Email,Contact,Address,DOB,Discipiline,Batch)values(?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement pst1=obj.db.prepareStatement(q);
                pst1.setString(1, u);
                pst1.setString(2, p);
                pst1.setString(3, sq);
                pst1.setString(4, sa);
                pst1.setString(5, e);
                pst1.setString(6, c);
                pst1.setString(7, ad);
                pst1.setString(8, u1);
                pst1.setString(9, d);
                pst1.setString(10, b);
                pst1.executeUpdate();
                Login obj2=new Login();
                obj2.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"username not available");
            }
        }
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField t1;
    private java.awt.TextField t10;
    private java.awt.TextField t11;
    private java.awt.TextField t2;
    private java.awt.Choice t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    private java.awt.TextField t6;
    private java.awt.TextField t7;
    private java.awt.TextField t8;
    private com.toedter.calendar.JDateChooser t9;
    // End of variables declaration//GEN-END:variables
}
