/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author DELL
 */
public class TechnicalAttributes extends javax.swing.JFrame {
    public static boolean eduBoo = false,acadBoo = false,schBoo = false,pubBoo = false,resBoo = false,confBoo = false,certiBoo = false,internBoo = false,posBoo = false,extraBoo = false,entreBoo = false,miscBoo = false;

    /**
     * Creates new form TechnicalAttributes
     */
    public TechnicalAttributes() {
        initComponents();
         setBounds(500, 500, 600, 450);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        education = new javax.swing.JCheckBox();
        academic = new javax.swing.JCheckBox();
        scholastic = new javax.swing.JCheckBox();
        publications = new javax.swing.JCheckBox();
        research = new javax.swing.JCheckBox();
        conferences = new javax.swing.JCheckBox();
        certifications = new javax.swing.JCheckBox();
        internships = new javax.swing.JCheckBox();
        positions = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        extraCurricular = new javax.swing.JCheckBox();
        entrepreneurship = new javax.swing.JCheckBox();
        miscellaneous = new javax.swing.JCheckBox();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Please Select the Attributes You Want in Your Resume");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(157, 19, 419, 21);

        education.setBackground(new java.awt.Color(255, 255, 255));
        education.setText("Educational qualifications");
        education.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educationActionPerformed(evt);
            }
        });
        getContentPane().add(education);
        education.setBounds(150, 73, 220, 23);

        academic.setBackground(new java.awt.Color(255, 255, 255));
        academic.setText("Academic Achievements");
        getContentPane().add(academic);
        academic.setBounds(150, 96, 210, 26);

        scholastic.setBackground(new java.awt.Color(255, 255, 255));
        scholastic.setText("Scholastic Achievements");
        getContentPane().add(scholastic);
        scholastic.setBounds(150, 122, 210, 23);

        publications.setBackground(new java.awt.Color(255, 255, 255));
        publications.setText("Publications");
        publications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicationsActionPerformed(evt);
            }
        });
        getContentPane().add(publications);
        publications.setBounds(150, 145, 210, 23);

        research.setBackground(new java.awt.Color(255, 255, 255));
        research.setText("Sponsored Research Projects");
        getContentPane().add(research);
        research.setBounds(150, 171, 220, 23);

        conferences.setBackground(new java.awt.Color(255, 255, 255));
        conferences.setText("Conferences/Workshops Attended");
        conferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferencesActionPerformed(evt);
            }
        });
        getContentPane().add(conferences);
        conferences.setBounds(150, 197, 220, 23);

        certifications.setBackground(new java.awt.Color(255, 255, 255));
        certifications.setText("Certifications");
        getContentPane().add(certifications);
        certifications.setBounds(150, 220, 100, 23);

        internships.setBackground(new java.awt.Color(255, 255, 255));
        internships.setText("Internships");
        internships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internshipsActionPerformed(evt);
            }
        });
        getContentPane().add(internships);
        internships.setBounds(150, 243, 90, 23);

        positions.setBackground(new java.awt.Color(255, 255, 255));
        positions.setText("Position of Responsibility");
        getContentPane().add(positions);
        positions.setBounds(150, 266, 200, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 140, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TECHNICAL ASSISTANCE.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 100, 120);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        extraCurricular.setBackground(new java.awt.Color(255, 255, 255));
        extraCurricular.setText("Extra Curricular Activities");

        entrepreneurship.setBackground(new java.awt.Color(255, 255, 255));
        entrepreneurship.setText("Entrepreneurship");

        miscellaneous.setBackground(new java.awt.Color(255, 255, 255));
        miscellaneous.setText("Miscellaneous");

        b1.setText("Back");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("Next");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(396, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(extraCurricular, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(entrepreneurship, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(miscellaneous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(extraCurricular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrepreneurship)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miscellaneous)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2))
                .addGap(70, 70, 70))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void educationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_educationActionPerformed

    private void publicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publicationsActionPerformed

    private void conferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conferencesActionPerformed

    private void internshipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internshipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internshipsActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new TechnicalTemplate().setVisible(true);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(education.isSelected())
        {
            eduBoo =  true;
            
        }
        if(academic.isSelected())
        {
            acadBoo =  true;
        }
        if(scholastic.isSelected())
        {
            schBoo =  true;
        }
        if(publications.isSelected())
        {
            pubBoo =  true;
        }
        if(research.isSelected())
        {
            resBoo =  true;
        }
        if(conferences.isSelected())
        {
            confBoo =  true;
        }
        if(certifications.isSelected())
        {
            certiBoo =  true;
        }
        if(internships.isSelected())
        {
            internBoo =  true;
        }
        if(positions.isSelected())
        {
            posBoo =  true;
        }
        if(extraCurricular.isSelected())
        {
            extraBoo =  true;
        }
        if(entrepreneurship.isSelected())
        {
            entreBoo =  true;
        }
        if(miscellaneous.isSelected())
        {
            miscBoo =  true;
        }
        this.setVisible(false);
        new FillFormTechnical().setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechnicalAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechnicalAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechnicalAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechnicalAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TechnicalAttributes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox academic;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JCheckBox certifications;
    private javax.swing.JCheckBox conferences;
    private javax.swing.JCheckBox education;
    private javax.swing.JCheckBox entrepreneurship;
    private javax.swing.JCheckBox extraCurricular;
    private javax.swing.JCheckBox internships;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox miscellaneous;
    private javax.swing.JCheckBox positions;
    private javax.swing.JCheckBox publications;
    private javax.swing.JCheckBox research;
    private javax.swing.JCheckBox scholastic;
    // End of variables declaration//GEN-END:variables
}
